# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: NeuralProphet
version: "0.0.3"
slug: neuralprophet
description: NeuralProphet add-on
url: "https://github.com/sunnysideal/hass-addons/neuralprophet"
arch:
  - aarch64
  - amd64

init: false
map:
  - addon_config:rw
