# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: NeuralProphet
version: "0.2.4"
version: "0.2.5"
slug: neuralprophet
description: NeuralProphet add-on
url: "https://github.com/sunnysideal/hass-addons/neuralprophet"
arch:
  - aarch64
  - amd64

init: false
homeassistant_api: true
map:
  - addon_config:rw
